# Generated by Django 4.2.5 on 2025-12-24 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("Beginner", "Beginner"),
                            ("Medium", "Medium"),
                            ("Advanced", "Advanced"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("Fresher", "Fresher / < 1 Year"),
                            ("1-3 Years", "1 - 3 Years"),
                            ("4-5 Years", "4 - 5 Years"),
                            ("5+ Years", "Above 5 Years"),
                        ],
                        max_length=20,
                    ),
                ),
                ("num_questions", models.IntegerField()),
                ("repeated_questions_allowed", models.BooleanField(default=False)),
                ("mcq_format", models.BooleanField(default=False)),
                ("mcq_coding_format", models.BooleanField(default=False)),
                ("general_topic", models.BooleanField(default=False)),
                (
                    "coding_languages",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("specific_instructions", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
